### ISSUE TITLE
Filter seq cannot use symlink fastq file

### ISSUE THREAD

**Issue by Takadonet** [TGAC/KAT#63]
Started working on a Galaxy wrapper for filter seq and getting the following error  when running the command : filter seq input.fastq  -o reads db.jtf

Error: Unknown file extension of /tmp/tmpNs8Ym6/files/000/dataset_1.dat: iostream error

input.fastq is a soft link to /tmp/tmpNs8Ym6/files/000/dataset_1.dat . In Galaxy, all datasets have the same extension of .dat and cannot be changed. Is there a workaround that I am missing?

**Comment by Takadonet** [comment]
Seems that filter seq hard linking of the files works. Not sure if the best solution but it does work.

**Comment by maplesond** [comment]
There shouldn't be anything specifically that stops symlinks from working but thanks for pointing this out, I'll see if I can reproduce the issue and fix if necessary.  In general, this may be nothing to do with hard and softlinks and more to do with the file extension.  The way we distinguish between sequence files and jellyfish files is based purely on the file extension, so if the file extension doesn't end in  fastq, fq, fa, fna, fasta, fas or scafseq, then we assume it's a jellyfish hash.  This isn't ideal so it might be that we implement something that interrogates the first line of the file, i.e to look for '@' or '>' symbols.  This would allow you to work with .dat files more easily.

**Comment by maplesond** [comment]
I've pushed up a change on the development branch which should auto detect a fasta or fastq file from the first non-whitespace character in the file (i.e. whether it is '@' or '>').  Do you want to give this a go?  If it works it will be in the next release of KAT.

**Comment by Takadonet** [comment]
Still no go.

Getting the follow error.

$ kat filter works.fastq db.fasta 
Kmer Analysis Toolkit (KAT) V2.1.1

filter.cc(62): Throw in function static kat::Filter::FilterMode kat::Filter::parseMode(const string&)
Dynamic exception type: boost::exception_detail::clone_impl<KatFilterException>
std::exception::what: std::exception
[KatFilterError*] = Could not recognise mode string: works.fastq


Where works.fastq is a soft link that points to bad_ext.dat

**Comment by maplesond** [comment]
Ah, I see the problem now.  While I've fixed the problem for anywhere that I'm using jellyfish to count kmers, I'm still using SeqAn to load the sequence file in this case.  SeqAn still requires the extension to determine which parser to use.  I'll need to determine the actual file type myself, then feed this information directly to seqan rather than relying on its autodetection.  I'll update the ticket when I have a fix.

**Comment by maplesond** [comment]
Actually, this looks like it's not that easy to fix.  It seems like it's difficult to disable the auto format detection functionality in this version of seqan.  Either I'll need to figure out how to do this, or I'll throw out seqan and use home-made parsers, but this will take a while.  So unfortunately, you'll need to work around this issue with hardlinks for the time being.  I'll leave the case open until I've implemented a proper fix.

**Comment by Takadonet** [comment]
Thanks for looking into this issue. I am glad that my workaround is working so I can continue developing some galaxy wrappers for kat.

**Comment by Takadonet** [comment]
Curious to know if there is any progress on this issue? Workaround still works but don't like that I have to hard link files before using them.

**Comment by maplesond** [comment]
I think it's going to be the next major release before this one gets fixed.  The cleanest solution is to remove the seqan dependency and use our own FastQ/A handling code.

**Comment by Takadonet** [comment]
Sounds good. Thanks for the update.

**Comment by bjclavijo** [comment]
I don't think we will be fixing this issue, so I am closing it. Please keep using the workaround for this one.
